export const BillPayConstants = {
    PaymentQuestion: "Payment Question",
    ValidateIssue: "Please enter all Required Fields (*)",
    paymentIssue: "Payment amount mismatched. Please Re-Enter correct payment amount",
    DatePicker: "date-picker",
    MatchFieldValue: "matchFieldName",
    SetValidators: 'setValidators',
    PaymentIncomplete: "Payment - Incomplete",
    LargeGroupBillValidationMsg: "Additional Large Group Bill copies require payment data entry, payment data will be sent after all have been completed.",
    UBMGroupValidationMsg:"Additional UBM invoices require payment data entry, payment data will be sent after all have been completed.",
    Success: "Payment Data Sent",
    Hold: "Hold",
    GroupBill: "Not part of Group Bill",
    PaymentAccountSetupIssueException: "PaymentAccountSetupIssue",
    PaymentQuestionException: "PaymentQuestion",
    EditInvoice: "EditInvoice",
    Queue: "Queue",
    GrossValue: "GrossValue",
    BalanceBroughtForward: "BalanceBroughtForward",
    Deposit: "Deposit",
    MoreThanTwoDecimalMessage:"One or more charges/payment fields has more than two decimal places",
    NumberText:"Number Text",
    PaymentAmount:"Copy/Paste Disable Text",
    LargeGroupBill: "Large Group Bill",
    MoveSelectedOtherMonth: "Move Selected to Other Month",
    UBMGroup: "UBM Group",
    GroupPGI: "Group PGI",
    ParentImageId: "Parent Image Id",
    ApprovedVendorValidationMsg:"Approved Payment Vendor is different from other copies in the large group bill. Please check sibling invoices and use the same vendor."
}